import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
const inter = Montserrat({ subsets: ["latin"] });
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-webColor`}>
       
               {children}
       
      </body>
    </html>
  );
}
